version: "3.8"

services:
  mysql:
    image: mysql
    restart: on-failure:3
    env_file: ./.env
    environment:
      MYSQL_USER: $MYSQL_USERNAME
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    ports:
      - $MYSQL_LOCAL_PORT:${MYSQL_DOCKER_PORT}
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 30s
      timeout: 30s
      retries: 3
  app:
    depends_on:
      mysql:
        condition: service_healthy
    restart: on-failure
    image: book-store-app
    build: .
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
      - $DEBUG_PORT:$DEBUG_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:mysql://mysql:${MYSQL_DOCKER_PORT}/$MYSQL_DATABASE",
        "spring.datasource.username" : "${MYSQL_USERNAME}",
        "spring.datasource.password" : "${MYSQL_PASSWORD}",
        "jwt.expiration" : "${JWT_EXPIRATION}",
        "jwt.secret" : "${JWT_SECRET}"
      }'
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:${DEBUG_PORT}"
